esphome:
  name: chair-display
  friendly_name: chair-display.yaml
  platformio_options:
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal
  speed: 80MHz      

# Enable logging
logger:

packages:
  fonts_images: !include chair-display/cd_fonts_images.yaml
  lvgl: !include chair-display/cd_lvgl.yaml
  hardware: !include chair-display/cd_hardware.yaml
  sensors: !include chair-display/cd_sensors.yaml
  substitutions: !include chair-display/cd_substitutions.yaml

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Chair-Displayyaml"
    password: "h2zGHYe1OYaQ"

web_server:
  port: 80
  version: 1


captive_portal:





